### ISSUE TITLE
Joints (keypoints) Order Configuration

### ISSUE THREAD

**Issue by yangchris11** [bastianwandt/CanonPose#1]
Interesting work!

After trying out your code with my own visualization, I noticed that the joint numbers in your work is set to 16. Therefore I wonder if you can provide the specific naming and ordering of the keypoints, thank you!

**Comment by bastianwandt** [comment]
Hi! Thanks for your interest in the work. 
We used our own preprocessing and joint ordering:
0 - rhip
1 - rknee
2 - rfoot
3 - lhip
4 - lknee
5 - lfoot
6 - root
7 - neck
8 - nose
9 - top_head
10 - rshoulder
11 - relbow
12 - rhand
13 - lshoulder
14 - lelbow
15 - lhand

Note that the names may not be consistent with names in common databases since we merged two different skeletons (output of Alphapose and the skeleton morphed to H36M/3DHP/SkiPose).

**Comment by yangchris11** [comment]
Thank you for your detailed explanation! 

(Just curious, is there any plan on releasing the evaluation portion of your work soon?)

**Comment by bastianwandt** [comment]
Unfortunately, the data is licensed so it's not possible to upload it.

**Comment by yangchris11** [comment]
I see. Thank you!
