### ISSUE TITLE
evaluation code and pretrained-model which could achieve metrics in paper

### ISSUE THREAD

**Issue by linye-boli** [bastianwandt/CanonPose#2]
Hello, before you releasing this official code, I tried to code this algorithm by myself but the performance is not good. It will be very useful if you could provide evaluation code relates to MPJPE, PMPJPE calculation, thx

**Comment by bastianwandt** [comment]
Hi,
due to licensing reasons it's not possible to share data. The (P)MPJPE, PCK and CPS calculation is done as in every other human pose estimation paper. 
MPJPE: Mean euclidean distance between joints. P: with procrustes alignment.
PCK: Percentage of keypoints with a distance less than 150mm to the GT
CPS: Percentage of Poses where all keypoints are within a threshold. This is an area under curve as described in the paper.

I hope this helps.
Bastian

**Comment by linye-boli** [comment]
> Hi,
> due to licensing reasons it's not possible to share data. The (P)MPJPE, PCK and CPS calculation is done as in every other human pose estimation paper.
> MPJPE: Mean euclidean distance between joints. P: with procrustes alignment.
> PCK: Percentage of keypoints with a distance less than 150mm to the GT
> CPS: Percentage of Poses where all keypoints are within a threshold. This is an area under curve as described in the paper.
> 
> I hope this helps.
> Bastian

Thanks for your reply, I notice the order of joints is special, will that change the performance?

**Comment by bastianwandt** [comment]
No, the joint ordering has no influence on the performance. These are the joint ID's:
0 - rhip
1 - rknee
2 - rfoot
3 - lhip
4 - lknee
5 - lfoot
6 - root
7 - neck
8 - nose
9 - top_head
10 - rshoulder
11 - relbow
12 - rhand
13 - lshoulder
14 - lelbow
15 - lhand

**Comment by linye-boli** [comment]
I see, thank you

**Comment by maicao2018** [comment]
Hi, @bastianwandt

Do the **predicted pose** and **target pose** need to be Procrustes aligned before calculating 3DPCK?

Thanks.
